  SELECT * FROM API7.EMPLOYE;
--
  SELECT MAT, NOM,
    'NO DEPT : ', NOD, DAT,              SAL,       COM
  FROM API7.EMPLOYE;
--
  SELECT *
  FROM API7.EMPLOYE
    ORDER BY NOD;
--
  SELECT *
  FROM API7.EMPLOYE
    ORDER BY COM;
--
  SELECT * FROM API7.EMPLOYE WHERE NOM > 'GARBOT';
--
  SELECT * FROM API7.EMPLOYE WHERE NOM <> 'GARBOT';
--
  SELECT * FROM API7.EMPLOYE WHERE NOM != 'GARBOT';
--
  SELECT * FROM API7.EMPLOYE WHERE NOM = 'GARBOT';
--
  SELECT * FROM API7.EMPLOYE WHERE NOM IN ('GARBOT','IONOS');
--
  SELECT * FROM API7.EMPLOYE WHERE NOM NOT IN ('GARBOT','IONOS');
--
  SELECT * FROM API7.EMPLOYE WHERE NOM BETWEEN 'ALLU' AND 'FEU';
--
  SELECT * FROM API7.EMPLOYE WHERE COM IS NULL;
--
  SELECT * FROM API7.EMPLOYE WHERE COM IS NOT NULL;
--
  SELECT * FROM API7.EMPLOYE WHERE NOM LIKE '%A%';



