---VALEUR DU STOCK PAR DECLINAISON
 --
   SELECT ID_ARTICL , ID_DECLINAISON ,
     STOCK , PRIX, STOCK * PRIX AS VALEUR
     FROM ARTICLE A ,
       DECLINAISON D
     WHERE A.ID_ARTICLE = D.ID_ARTICL
     ;
