--DROP  TABLE ARTICLE;
--COMMIT ;
-- CREATION DE LA TABLE ARTICLE
CREATE    TABLE ARTICLE(
 ID_ARTICLE  INTEGER NOT NULL,
 DESIGNATION  CHAR(20) NOT NULL,
 PRIX         DECIMAL(5,2) NOT NULL,
 ID_MARQUE    CHAR(2),
 ID_FAMILLE   CHAR(2) NOT NULL,
 PRIMARY KEY (ID_ARTICLE),
   FOREIGN KEY (ID_FAMILLE) REFERENCES FAMILLE (ID_FAMILLE)
     ON DELETE RESTRICT,
   FOREIGN KEY (ID_MARQUE) REFERENCES MARQUE (ID_MARQUE)
     ON DELETE SET NULL
)  IN APIETUDE.API7;
CREATE UNIQUE INDEX PK_ARTICLE
 ON ARTICLE (ID_ARTICLE) ;
--
COMMIT;






