--- VALEUR DU STOCK PAR ARTICLE
--

SELECT ID_ARTICL
-- , STOCK , PRIX, STOCK * PRIX AS VALEUR
, SUM(STOCK * PRIX) AS VALEUR
FROM ARTICLE A
, DECLINAISON D
WHERE A.ID_ARTICLE = D.ID_ARTICL
GROUP BY ID_ARTICL
;



