--DROP TABLE MARQUE;
--COMMIT;
-- CREATION DE LA TABLE MARQUE
CREATE    TABLE MARQUE(
 ID_MARQUE   CHAR(02) NOT NULL,
 DESIGNATION  CHAR(20) NOT NULL,
 PRIMARY KEY  (ID_MARQUE)
)   IN APIETUDE.API7;
CREATE UNIQUE INDEX PK_MARQUE
 ON MARQUE (ID_MARQUE) ;
--
COMMIT;
