--DROP TABLE DECLINAISON;
--COMMIT;
-- CREATION DE LA TABLE DECLINAISON
CREATE    TABLE DECLINAISON(
 ID_ARTICL INTEGER NOT NULL,
 ID_DECLINAISON CHAR(02) NOT NULL,
 DESIGNATION  CHAR(20) NOT NULL,
 STOCK        INTEGER NOT NULL WITH DEFAULT 0,
 STOCK_ALERTE INTEGER NOT NULL WITH DEFAULT 0,
 TAILLE       CHAR(05) NOT NULL,
 COLORIS      CHAR(10) NOT NULL,
 QUOTITE      INTEGER NOT NULL WITH DEFAULT 1,
 STOCK_COMMANDEE  INTEGER NOT NULL WITH DEFAULT 0,
 PRIMARY KEY  (ID_ARTICL,ID_DECLINAISON),
  FOREIGN KEY (ID_ARTICL)  REFERENCES ARTICLE (ID_ARTICLE)
   ON DELETE CASCADE
   )   IN APIETUDE.API7;

   CREATE UNIQUE INDEX PK_DECLINAISON
    ON DECLINAISON (ID_ARTICL,ID_DECLINAISON) ;
   --
   COMMIT;





