--DROP TABLE ENTREPOT;
--COMMIT;
-- CREATION DE LA TABLE ENTREPOT
CREATE    TABLE ENTREPOT(
 ID_ENTREPOT CHAR(02) NOT NULL,
 DESIGNATION  CHAR(20) NOT NULL,
 PRIMARY KEY  (ID_ENTREPOT)
)   IN APIETUDE.API7;
CREATE UNIQUE INDEX PK_ENTREPOT
 ON ENTREPOT (ID_ENTREPOT) ;
--
COMMIT;
