//API7JSOM JOB (ACCT#),'ALEXIS',MSGCLASS=H,REGION=4M,
// CLASS=A,MSGLEVEL=(1,1),NOTIFY=&SYSUID,COND=(4,LT)
//*
//* ETAPE DE COMPILATION
//*
//COMPIL   EXEC IGYWCL,PARM.COBOL=(NODYNAM,ADV,OBJECT,LIB,TEST,APOST)
//COBOL.SYSIN  DD DSN=API7.SOURCE.COBOL(SOM),DISP=SHR
//COBOL.SYSLIB DD DSN=CEE.SCEESAMP,DISP=SHR
//             DD DSN=API7.SOURCE.COPY,DISP=SHR
//*
//* ETAPE DE LINKEDIT
//*
//LKED.SYSLMOD DD DSN=API7.COBOL.LOAD,DISP=(SHR,KEEP,KEEP)
//LKED.SYSIN DD *
 NAME SOM(R)
/*
