//API7EXO2 JOB (ACCT#),'ALEXIS',CLASS=A,MSGCLASS=H,MSGLEVEL=(1,1),
//             NOTIFY=&SYSUID,REGION=4M,TIME=(,30)
//* LISTER LE CONTENU FICHIER API7.AJC.EMPLOYE.DATA
//****************************************************************
//LISTER     EXEC PGM=IEBGENER
//SYSPRINT   DD SYSOUT=*
//SYSUT1     DD DSN=API7.AJC.EMPLOYE.DATA,DISP=SHR
//SYSUT2     DD SYSOUT=*
//SYSIN      DD DUMMY
//* COPIER LE CONTENU DU FICHIER API7.AJC.EMPLOYE.DATA DANS
//*                   LE FICHIER API7.AJC.FICTEST.DATA
//****************************************************************
//COPIE1     EXEC PGM=IEBGENER
//SYSPRINT   DD SYSOUT=*
//SYSUT1     DD DSN=API7.AJC.EMPLOYE.DATA,DISP=SHR
//SYSUT2     DD DSN=API7.AJC.FICTEST.DATA,DISP=SHR
//SYSIN      DD DUMMY
//* COPIER LE CONTENU DE API7.AJC.COMM.DATA ET
//*                      API7.AJC.COMMD.DATA
//* DANS LE FICHIER API7.AJC.COMMANDE.DATA (DE LONGUEUR
//*                                D'ENREGISTREMENT 25)
//****************************************************************
//COPIE2     EXEC PGM=IEBGENER
//SYSPRINT   DD SYSOUT=*
//SYSUT1     DD DSN=API7.AJC.COMM.DATA,DISP=SHR
//           DD DSN=API7.AJC.COMMD.DATA,DISP=SHR
//SYSUT2     DD DSN=API7.AJC.COMMANDE,DISP=(NEW,CATLG,DELETE),
//     DCB=(LRECL=25,RECFM=FB,BLKSIZE=250),DSORG=PS,
//     SPACE=(TRK,(3,2),RLSE)
//SYSIN      DD DUMMY
