-- DROP TABLE FAMILLE;
-- COMMIT;
-- CREATION DE LA TABLE FAMILLE
CREATE    TABLE FAMILLE(
 ID_FAMILLE  CHAR(02) NOT NULL,
 DESIGNATION  CHAR(20) NOT NULL ,
 ID_ENTREPOT  CHAR(02) NOT NULL,
 PRIMARY KEY  (ID_FAMILLE),
   FOREIGN KEY (ID_ENTREPOT) REFERENCES ENTREPOT (ID_ENTREPOT)
   ON DELETE RESTRICT
)   IN APIETUDE.API7;
CREATE UNIQUE INDEX PK_FAMILLE
 ON FAMILLE (ID_FAMILLE) ;
--
COMMIT;
