SELECT ID_ARTICLE, ID_DECLINAISON , STOCK , PRIX
  FROM ARTICLE;

SELECT D.ID_ARTICLE, ID_DECLINAISON , D.STOCK , A.PRIX
  FROM ARTICLE A, D;

SELECT D.ID_ARTICLE, ID_DECLINAISON , D.STOCK , A.PRIX
  FROM ARTICLE A, D;

SELECT D.ID_ARTICLE, ID_DECLINAISON , D.STOCK , A.PRIX, STOCK* PRIX
  AS V;

