  SELECT * FROM API7.DEPARTEMENTS D,
    API7.EMPLOYE E
  WHERE D.NOD = E.NOD;
--
  SELECT D.NOD, E.NOD, E.*
    FROM API7.DEPARTEMENTS D,
    API7.EMPLOYE E
  WHERE D.NOD = E.NOD;
--
  SELECT CURRENT DATE FROM SYSIBM.SYSDUMMY1;
  SELECT CURRENT TIME FROM SYSIBM.SYSDUMMY1;
  SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;
--
--SELECT YEAR (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT MONTH (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT DATE (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT TIME (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT DAY (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT HOUR (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT MINUTE (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT SECOND (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--SELECT MICROSECOND (CURRENT TIMESTAMP) FROM SYSIMB.SYSDUMMY1;
--
  SELECT DISTINCT NOD FROM API7.DEPARTEMENTS;
--
  SELECT NOD, SUM(COM) FROM API7.EMPLOYE GROUP BY NOD;
--
  SELECT COUNT(*) FROM EMPLOYE;
--
  SELECT NOD, COUNT(*) FROM EMPLOYE GROUP BY NOD;
--
  SELECT NOD, SUM(SAL)
    FROM API7.EMPLOYE
    GROUP BY NOD
    HAVING SUM(SAL) > 2000;
--
  SELECT NOD, 'EMPLOYE ', NOM FROM EMPLOYE
  UNION ALL
  SELECT NOD, 'DEPARTEMENT ', NDE FROM DEPARTEMENTS
  ORDER BY 1, 3;
--
  SELECT NOM, SAL
  FROM EMPLOYE
  WHERE SAL * 12 < 120000 AND VALUE (COM,0) < (SAL/3);
--
  SELECT * FROM DEPARTEMENTS
  WHERE NOD
    IN (
      SELECT NOD
        FROM EMPLOYE
       WHERE SAL > 10000
       );
--
  SELECT * FROM EMPLOYE ORDER BY MAT;
--
  SELECT MAT,
         MIN(SAL) AS MIN,
         MAX(SAL) AS MAX,
         SUM(SAL) AS SUM,
         AVG(SAL) AS AVG
  FROM EMPLOYE GROUP BY MAT ORDER BY MAT;
--
  SELECT MAX(SAL) FROM EMPLOYE;
--
  SELECT MAX(SAL),NOM FROM EMPLOYE GROUP BY NOM;








